language: go
go:
  - "1.12.x"
  - "1.13.x"

go_import_path: github.com/markphelps/optional

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

env:
  - GO111MODULE=on

before_script: make setup
script: make ci

notifications:
  email: false
