// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2017-07-15 19:06:13.872843788 +0000 UTC
package optional

// Byte is an optional byte
type Byte struct {
	byte
	present bool
}

// OfByte creates an optional.Byte from a byte
func OfByte(b byte) Byte {
	return Byte{byte: b, present: true}
}

// Set sets the byte value
func (o *Byte) Set(b byte) {
	o.byte = b
	o.present = true
}

// Byte returns the byte value
func (o *Byte) Byte() byte {
	return o.byte
}

// Present returns whether or not the value is present
func (o *Byte) Present() bool {
	return o.present
}

// OrElse returns the value or a default value if the value is not present
func (o *Byte) OrElse(b byte) byte {
	if o.present {
		return o.byte
	}
	return b
}
