// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2017-07-23 21:16:21.940473128 +0000 UTC

package optional

// Complex128 is an optional complex128
type Complex128 struct {
	complex128 complex128
	present    bool
}

// EmptyComplex128 returns an empty optional.Complex128
func EmptyComplex128() Complex128 {
	return Complex128{}
}

// OfComplex128 creates an optional.Complex128 from a complex128
func OfComplex128(c complex128) Complex128 {
	return Complex128{complex128: c, present: true}
}

// Set sets the complex128 value
func (o *Complex128) Set(c complex128) {
	o.complex128 = c
	o.present = true
}

// Complex128 returns the complex128 value
func (o *Complex128) Complex128() complex128 {
	return o.complex128
}

// Present returns whether or not the value is present
func (o *Complex128) Present() bool {
	return o.present
}

// OrElse returns the complex128 value or a default value if the value is not present
func (o *Complex128) OrElse(c complex128) complex128 {
	if o.present {
		return o.complex128
	}
	return c
}
