//go:generate go run cmd/optional/main.go bool Bool
//go:generate go run cmd/optional/main.go string String
//go:generate go run cmd/optional/main.go int Int
//go:generate go run cmd/optional/main.go int8 Int8
//go:generate go run cmd/optional/main.go int16 Int16
//go:generate go run cmd/optional/main.go int32 Int32
//go:generate go run cmd/optional/main.go int64 Int64
//go:generate go run cmd/optional/main.go uint Uint
//go:generate go run cmd/optional/main.go uint8 Uint8
//go:generate go run cmd/optional/main.go uint16 Uint16
//go:generate go run cmd/optional/main.go uint32 Uint32
//go:generate go run cmd/optional/main.go uint64 Uint64
//go:generate go run cmd/optional/main.go uintptr Uintptr
//go:generate go run cmd/optional/main.go byte Byte
//go:generate go run cmd/optional/main.go rune Rune
//go:generate go run cmd/optional/main.go float32 Float32
//go:generate go run cmd/optional/main.go float64 Float64
//go:generate go run cmd/optional/main.go complex64 Complex64
//go:generate go run cmd/optional/main.go complex128 Complex128
