// Code generated by go generate
// This file was generated by robots at 2018-03-25 18:09:19.517048587 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Int is an optional int
type Int struct {
	value *int
}

// NewInt creates a optional.Int from a int
func NewInt(v int) Int {
	return Int{&v}
}

// Set sets the int value
func (i Int) Set(v int) {
	i.value = &v
}

// Get returns the int value or an error if not present
func (i Int) Get() (int, error) {
	if !i.Present() {
		return *i.value, errors.New("value not present")
	}
	return *i.value, nil
}

// Present returns whether or not the value is present
func (i Int) Present() bool {
	return i.value != nil
}

// OrElse returns the int value or a default value if the value is not present
func (i Int) OrElse(v int) int {
	if i.Present() {
		return *i.value
	}
	return v
}

// If calls the function f with the value if the value is present
func (i Int) If(fn func(int)) {
	if i.Present() {
		fn(*i.value)
	}
}

func (i Int) MarshalJSON() ([]byte, error) {
	if i.Present() {
		return json.Marshal(i.value)
	}
	return nil, nil
}

func (i *Int) UnmarshalJSON(data []byte) error {
	if len(data) < 1 {
		i.value = nil
		return nil
	}

	i.value = new(int)
	return json.Unmarshal(data, i.value)
}
