// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2017-07-23 21:16:17.706403073 +0000 UTC

package optional

// Int8 is an optional int8
type Int8 struct {
	int8    int8
	present bool
}

// EmptyInt8 returns an empty optional.Int8
func EmptyInt8() Int8 {
	return Int8{}
}

// OfInt8 creates an optional.Int8 from a int8
func OfInt8(i int8) Int8 {
	return Int8{int8: i, present: true}
}

// Set sets the int8 value
func (o *Int8) Set(i int8) {
	o.int8 = i
	o.present = true
}

// Int8 returns the int8 value
func (o *Int8) Int8() int8 {
	return o.int8
}

// Present returns whether or not the value is present
func (o *Int8) Present() bool {
	return o.present
}

// OrElse returns the int8 value or a default value if the value is not present
func (o *Int8) OrElse(i int8) int8 {
	if o.present {
		return o.int8
	}
	return i
}
