// Code generated by go generate
// This file was generated by robots at 2021-05-04 14:21:59.22585 +0000 UTC

package optional

import (
	"encoding/json"
	"errors"
)

// Uint16 is an optional uint16.
type Uint16 struct {
	value *uint16
}

// NewUint16 creates an optional.Uint16 from a uint16.
func NewUint16(v uint16) Uint16 {
	return Uint16{&v}
}

// Set sets the uint16 value.
func (u *Uint16) Set(v uint16) {
	u.value = &v
}

// Get returns the uint16 value or an error if not present.
func (u Uint16) Get() (uint16, error) {
	if !u.Present() {
		var zero uint16
		return zero, errors.New("value not present")
	}
	return *u.value, nil
}

// MustGet returns the uint16 value or panics if not present.
func (u Uint16) MustGet() uint16 {
	if !u.Present() {
		panic("value not present")
	}
	return *u.value
}

// Present returns whether or not the value is present.
func (u Uint16) Present() bool {
	return u.value != nil
}

// OrElse returns the uint16 value or a default value if the value is not present.
func (u Uint16) OrElse(v uint16) uint16 {
	if u.Present() {
		return *u.value
	}
	return v
}

// If calls the function f with the value if the value is present.
func (u Uint16) If(fn func(uint16)) {
	if u.Present() {
		fn(*u.value)
	}
}

func (u Uint16) MarshalJSON() ([]byte, error) {
	if u.Present() {
		return json.Marshal(u.value)
	}
	return json.Marshal(nil)
}

func (u *Uint16) UnmarshalJSON(data []byte) error {

	if string(data) == "null" {
		u.value = nil
		return nil
	}

	var value uint16

	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	u.value = &value
	return nil
}
