// Code generated by go generate
// This file was generated by robots at 2017-07-25 13:05:49.219559938 +0000 UTC

package optional

// Uint is an optional uint
type Uint struct {
	uint    uint
	present bool
}

// EmptyUint returns an empty optional.Uint
func EmptyUint() Uint {
	return Uint{}
}

// OfUint creates a optional.Uint from a uint
func OfUint(u uint) Uint {
	return Uint{uint: u, present: true}
}

// Set sets the uint value
func (o *Uint) Set(u uint) {
	o.uint = u
	o.present = true
}

// Get returns the uint value
func (o *Uint) Get() uint {
	return o.uint
}

// Present returns whether or not the value is present
func (o *Uint) Present() bool {
	return o.present
}

// OrElse returns the uint value or a default value if the value is not present
func (o *Uint) OrElse(u uint) uint {
	if o.present {
		return o.uint
	}
	return u
}

// If calls the function f with the value if the value is present
func (o *Uint) If(f func(u uint)) {
	if o.present {
		f(o.uint)
	}
}
