// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2017-07-15 19:06:12.273237303 +0000 UTC
package optional

// Uint is an optional uint
type Uint struct {
	uint
	present bool
}

// OfUint creates an optional.Uint from a uint
func OfUint(u uint) Uint {
	return Uint{uint: u, present: true}
}

// Set sets the uint value
func (o *Uint) Set(u uint) {
	o.uint = u
	o.present = true
}

// Uint returns the uint value
func (o *Uint) Uint() uint {
	return o.uint
}

// Present returns whether or not the value is present
func (o *Uint) Present() bool {
	return o.present
}

// OrElse returns the value or a default value if the value is not present
func (o *Uint) OrElse(u uint) uint {
	if o.present {
		return o.uint
	}
	return u
}
