// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2017-07-15 19:25:43.409531156 +0000 UTC

package optional

// Uint32 is an optional uint32
type Uint32 struct {
	uint32
	present bool
}

// EmptyUint32 returns an empty optional.Uint32
func EmptyUint32() Uint32 {
	return Uint32{}
}

// OfUint32 creates an optional.Uint32 from a uint32
func OfUint32(u uint32) Uint32 {
	return Uint32{uint32: u, present: true}
}

// Set sets the uint32 value
func (o *Uint32) Set(u uint32) {
	o.uint32 = u
	o.present = true
}

// Uint32 returns the uint32 value
func (o *Uint32) Uint32() uint32 {
	return o.uint32
}

// Present returns whether or not the value is present
func (o *Uint32) Present() bool {
	return o.present
}

// OrElse returns the uint32 value or a default value if the value is not present
func (o *Uint32) OrElse(u uint32) uint32 {
	if o.present {
		return o.uint32
	}
	return u
}
