// Code generated by go generate
// This file was generated by robots at 2017-10-01 20:30:14.314147242 +0000 UTC

package optional

import "errors"

// Uint32 is an optional uint32
type Uint32 struct {
	value *uint32
}

// OfUint32 creates a optional.Uint32 from a uint32
func OfUint32(v uint32) Uint32 {
	return Uint32{&v}
}

// Set sets the uint32 value
func (u Uint32) Set(v uint32) {
	u.value = &v
}

// Get returns the uint32 value or an error if not present
func (u Uint32) Get() (uint32, error) {
	if u.value == nil {
		return *u.value, errors.New("value not present")
	}
	return *u.value, nil
}

// Present returns whether or not the value is present
func (u Uint32) Present() bool {
	return u.value != nil
}

// OrElse returns the uint32 value or a default value if the value is not present
func (u Uint32) OrElse(v uint32) uint32 {
	if u.Present() {
		return *u.value
	}
	return v
}

// If calls the function f with the value if the value is present
func (u Uint32) If(fn func(uint32)) {
	if u.Present() {
		fn(*u.value)
	}
}
