// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2017-07-15 19:25:43.183589076 +0000 UTC

package optional

// Uint16 is an optional uint16
type Uint16 struct {
	uint16
	present bool
}

// EmptyUint16 returns an empty optional.Uint16
func EmptyUint16() Uint16 {
	return Uint16{}
}

// OfUint16 creates an optional.Uint16 from a uint16
func OfUint16(u uint16) Uint16 {
	return Uint16{uint16: u, present: true}
}

// Set sets the uint16 value
func (o *Uint16) Set(u uint16) {
	o.uint16 = u
	o.present = true
}

// Uint16 returns the uint16 value
func (o *Uint16) Uint16() uint16 {
	return o.uint16
}

// Present returns whether or not the value is present
func (o *Uint16) Present() bool {
	return o.present
}

// OrElse returns the uint16 value or a default value if the value is not present
func (o *Uint16) OrElse(u uint16) uint16 {
	if o.present {
		return o.uint16
	}
	return u
}
