// Code generated by 'go generate'

package foo

import (
	"encoding/json"
	"errors"
)

// OptionalFoo is an optional Foo.
type OptionalFoo struct {
	value *Foo
}

// NewOptionalFoo creates an optional.OptionalFoo from a Foo.
func NewOptionalFoo(v Foo) OptionalFoo {
	return OptionalFoo{&v}
}

// NewOptionalFooFromPtr creates an optional.OptionalFoo from a Foo pointer.
func NewOptionalFooFromPtr(v *Foo) OptionalFoo {
	if v == nil {
		return OptionalFoo{}
	}
	return NewOptionalFoo(*v)
}

// Set sets the Foo value.
func (o *OptionalFoo) Set(v Foo) {
	o.value = &v
}

// ToPtr returns a *Foo of the value or nil if not present.
func (o OptionalFoo) ToPtr() *Foo {
	if !o.Present() {
		return nil
	}
	v := *o.value
	return &v
}

// Get returns the Foo value or an error if not present.
func (o OptionalFoo) Get() (Foo, error) {
	if !o.Present() {
		var zero Foo
		return zero, errors.New("value not present")
	}
	return *o.value, nil
}

// MustGet returns the Foo value or panics if not present.
func (o OptionalFoo) MustGet() Foo {
	if !o.Present() {
		panic("value not present")
	}
	return *o.value
}

// Present returns whether or not the value is present.
func (o OptionalFoo) Present() bool {
	return o.value != nil
}

// OrElse returns the Foo value or a default value if the value is not present.
func (o OptionalFoo) OrElse(v Foo) Foo {
	if o.Present() {
		return *o.value
	}
	return v
}

// If calls the function f with the value if the value is present.
func (o OptionalFoo) If(fn func(Foo)) {
	if o.Present() {
		fn(*o.value)
	}
}

func (o OptionalFoo) MarshalJSON() ([]byte, error) {
	if o.Present() {
		return json.Marshal(o.value)
	}
	return json.Marshal(nil)
}

func (o *OptionalFoo) UnmarshalJSON(data []byte) error {

	if string(data) == "null" {
		o.value = nil
		return nil
	}

	var value Foo

	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	o.value = &value
	return nil
}
