package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"
	"time"
)

var funcMap = template.FuncMap{
	"title": strings.Title,
	"first": func(s string) string {
		return string(s[0])
	},
}

const tmpl = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at {{ .Timestamp }}
package optional

type {{ .Name | title }} struct {
	{{ .Type }}
	present bool
}

func Of{{ .Type | title }}({{ .Type | first }} {{ .Type }}) {{ .Type | title }} {
	return {{ .Type | title }}{ {{ .Type }}: {{ .Type | first }}, present: true}
}

func (o *{{ .Name | title }}) Set({{ .Type | first }} {{ .Type }}) {
	o.{{ .Type }} = {{ .Type | first }}
	o.present = true
}

func (o *{{ .Name | title }}) {{ .Type | title }}() {{ .Type }} {
	return o.{{ .Type }}
}

func (o *{{ .Name | title }}) Present() bool {
	return o.present
}

func (o *{{ .Name | title }}) OrElse({{ .Type | first }} {{ .Type }}) {{ .Type }} {
	if o.present {
		return o.{{ .Type }}
	}
	return {{ .Type | first }}
}`

func main() {
	args := os.Args[1:]
	if len(args) < 1 {
		log.Fatalf("type is required")
	}

	typ := args[0]
	name := typ

	if len(args) > 1 {
		name = args[1]
	}

	t := template.Must(template.New("").Funcs(funcMap).Parse(tmpl))

	data := struct {
		Timestamp time.Time
		Type      string
		Name      string
	}{
		time.Now(),
		typ,
		name,
	}

	var buf bytes.Buffer

	err := t.Execute(&buf, data)
	if err != nil {
		log.Fatal(err)
	}

	p, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	f, err := os.Create(name + ".go")
	if err != nil {
		log.Fatal(err)
	}

	_, err = f.Write(p)
	if err != nil {
		log.Fatal(err)
	}
}
