name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53

    - name: "Lint & Test"
      run: make ci
